/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Tag from './Tag';

/**
* The ArticleDto model module.
* @module model/ArticleDto
* @version v1
*/
export default class ArticleDto {
    /**
    * Constructs a new <code>ArticleDto</code>.
    * @alias module:model/ArticleDto
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ArticleDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ArticleDto} obj Optional instance to populate.
    * @return {module:model/ArticleDto} The populated <code>ArticleDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArticleDto();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [Tag]);
            }
            if (data.hasOwnProperty('review')) {
                obj['review'] = ApiClient.convertToType(data['review'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {String} content
    */
    'content' = undefined;
    /**
    * @member {Array.<module:model/Tag>} tags
    */
    'tags' = undefined;
    /**
    * @member {Boolean} review
    */
    'review' = undefined;




}
