/*
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Tag} from './Tag';

/**
 * The ArticleRecordRequest model module.
 * @module model/ArticleRecordRequest
 * @version v1
 */
export class ArticleRecordRequest {
  /**
   * Constructs a new <code>ArticleRecordRequest</code>.
   * @alias module:model/ArticleRecordRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ArticleRecordRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArticleRecordRequest} obj Optional instance to populate.
   * @return {module:model/ArticleRecordRequest} The populated <code>ArticleRecordRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArticleRecordRequest();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('taggedContent'))
        obj.taggedContent = ApiClient.convertToType(data['taggedContent'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], [Tag]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ArticleRecordRequest.prototype.id = undefined;

/**
 * @member {String} taggedContent
 */
ArticleRecordRequest.prototype.taggedContent = undefined;

/**
 * @member {Array.<module:model/Tag>} tags
 */
ArticleRecordRequest.prototype.tags = undefined;

