/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TagArticleStatusEnum from './TagArticleStatusEnum';

/**
* The AuditArticleRequest model module.
* @module model/AuditArticleRequest
* @version v1
*/
export default class AuditArticleRequest {
    /**
    * Constructs a new <code>AuditArticleRequest</code>.
    * @alias module:model/AuditArticleRequest
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AuditArticleRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuditArticleRequest} obj Optional instance to populate.
    * @return {module:model/AuditArticleRequest} The populated <code>AuditArticleRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuditArticleRequest();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = TagArticleStatusEnum.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
            if (data.hasOwnProperty('auditorID')) {
                obj['auditorID'] = ApiClient.convertToType(data['auditorID'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {module:model/TagArticleStatusEnum} status
    */
    'status' = undefined;
    /**
    * @member {String} remark
    */
    'remark' = undefined;
    /**
    * @member {Number} auditorID
    */
    'auditorID' = undefined;




}
