/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TagArticleStatusEnum from './TagArticleStatusEnum';

/**
* The AuditRecord model module.
* @module model/AuditRecord
* @version v1
*/
export default class AuditRecord {
    /**
    * Constructs a new <code>AuditRecord</code>.
    * @alias module:model/AuditRecord
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AuditRecord</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuditRecord} obj Optional instance to populate.
    * @return {module:model/AuditRecord} The populated <code>AuditRecord</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuditRecord();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('cleanedArticleID')) {
                obj['cleanedArticleID'] = ApiClient.convertToType(data['cleanedArticleID'], 'Number');
            }
            if (data.hasOwnProperty('taggedRecordID')) {
                obj['taggedRecordID'] = ApiClient.convertToType(data['taggedRecordID'], 'Number');
            }
            if (data.hasOwnProperty('taskID')) {
                obj['taskID'] = ApiClient.convertToType(data['taskID'], 'Number');
            }
            if (data.hasOwnProperty('taggerID')) {
                obj['taggerID'] = ApiClient.convertToType(data['taggerID'], 'Number');
            }
            if (data.hasOwnProperty('auditorID')) {
                obj['auditorID'] = ApiClient.convertToType(data['auditorID'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = TagArticleStatusEnum.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
            if (data.hasOwnProperty('recordTime')) {
                obj['recordTime'] = ApiClient.convertToType(data['recordTime'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {Number} cleanedArticleID
    */
    'cleanedArticleID' = undefined;
    /**
    * @member {Number} taggedRecordID
    */
    'taggedRecordID' = undefined;
    /**
    * @member {Number} taskID
    */
    'taskID' = undefined;
    /**
    * @member {Number} taggerID
    */
    'taggerID' = undefined;
    /**
    * @member {Number} auditorID
    */
    'auditorID' = undefined;
    /**
    * @member {module:model/TagArticleStatusEnum} status
    */
    'status' = undefined;
    /**
    * @member {String} remark
    */
    'remark' = undefined;
    /**
    * @member {Date} recordTime
    */
    'recordTime' = undefined;




}
