/*
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class HttpCodeEnum.
 * @enum {Number}
 * @readonly
 */
const HttpCodeEnum = {
  /**
   * value: 100
   * @const
   */
  Info: 100,

  /**
   * value: 200
   * @const
   */
  Success: 200,

  /**
   * value: 300
   * @const
   */
  Warn: 300,

  /**
   * value: 500
   * @const
   */
  Error: 500,

  /**
   * Returns a <code>HttpCodeEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/HttpCodeEnum} The enum <code>HttpCodeEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {HttpCodeEnum};