/*
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class TagArticleStatusEnum.
 * @enum {Number}
 * @readonly
 */
const TagArticleStatusEnum = {
  /**
   * value: 0
   * @const
   */
  Untagged: 0,

  /**
   * value: 1
   * @const
   */
  Tagging: 1,

  /**
   * value: 2
   * @const
   */
  Tagged: 2,

  /**
   * value: 3
   * @const
   */
  Unaudited: 3,

  /**
   * value: 4
   * @const
   */
  Audited: 4,

  /**
   * value: 5
   * @const
   */
  Unsanctioned: 5,

  /**
   * value: 6
   * @const
   */
  Skiped: 6,

  /**
   * value: 7
   * @const
   */
  PreProcessed: 7,

  /**
   * value: 8
   * @const
   */
  Unavail: 8,

  /**
   * Returns a <code>TagArticleStatusEnum</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/TagArticleStatusEnum} The enum <code>TagArticleStatusEnum</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {TagArticleStatusEnum};