/*
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TaggedRecord} from './TaggedRecord';

/**
 * The TaggedRecordDto model module.
 * @module model/TaggedRecordDto
 * @version v1
 */
export class TaggedRecordDto {
  /**
   * Constructs a new <code>TaggedRecordDto</code>.
   * @alias module:model/TaggedRecordDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TaggedRecordDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TaggedRecordDto} obj Optional instance to populate.
   * @return {module:model/TaggedRecordDto} The populated <code>TaggedRecordDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TaggedRecordDto();
      if (data.hasOwnProperty('records'))
        obj.records = ApiClient.convertToType(data['records'], [TaggedRecord]);
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/TaggedRecord>} records
 */
TaggedRecordDto.prototype.records = undefined;

/**
 * @member {Number} total
 */
TaggedRecordDto.prototype.total = undefined;

