/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuditRecord from './AuditRecord';
import Auditor from './Auditor';
import TagArticleStatusEnum from './TagArticleStatusEnum';
import Tagger from './Tagger';

/**
* The TaggedRecord model module.
* @module model/TaggedRecord
* @version v1
*/
export default class TaggedRecord {
    /**
    * Constructs a new <code>TaggedRecord</code>.
    * @alias module:model/TaggedRecord
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TaggedRecord</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TaggedRecord} obj Optional instance to populate.
    * @return {module:model/TaggedRecord} The populated <code>TaggedRecord</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaggedRecord();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('cleanedArticleID')) {
                obj['cleanedArticleID'] = ApiClient.convertToType(data['cleanedArticleID'], 'String');
            }
            if (data.hasOwnProperty('taskID')) {
                obj['taskID'] = ApiClient.convertToType(data['taskID'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = TagArticleStatusEnum.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('statusRemark')) {
                obj['statusRemark'] = ApiClient.convertToType(data['statusRemark'], 'String');
            }
            if (data.hasOwnProperty('lastChangeTime')) {
                obj['lastChangeTime'] = ApiClient.convertToType(data['lastChangeTime'], 'Date');
            }
            if (data.hasOwnProperty('tagger')) {
                obj['tagger'] = Tagger.constructFromObject(data['tagger']);
            }
            if (data.hasOwnProperty('auditor')) {
                obj['auditor'] = Auditor.constructFromObject(data['auditor']);
            }
            if (data.hasOwnProperty('auditRecords')) {
                obj['auditRecords'] = ApiClient.convertToType(data['auditRecords'], [AuditRecord]);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {String} cleanedArticleID
    */
    'cleanedArticleID' = undefined;
    /**
    * @member {String} taskID
    */
    'taskID' = undefined;
    /**
    * @member {module:model/TagArticleStatusEnum} status
    */
    'status' = undefined;
    /**
    * @member {String} statusRemark
    */
    'statusRemark' = undefined;
    /**
    * @member {Date} lastChangeTime
    */
    'lastChangeTime' = undefined;
    /**
    * @member {module:model/Tagger} tagger
    */
    'tagger' = undefined;
    /**
    * @member {module:model/Auditor} auditor
    */
    'auditor' = undefined;
    /**
    * @member {Array.<module:model/AuditRecord>} auditRecords
    */
    'auditRecords' = undefined;




}
