/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TagArticleStatusEnum from './TagArticleStatusEnum';

/**
* The TaggedRecordPagerVm model module.
* @module model/TaggedRecordPagerVm
* @version v1
*/
export default class TaggedRecordPagerVm {
    /**
    * Constructs a new <code>TaggedRecordPagerVm</code>.
    * @alias module:model/TaggedRecordPagerVm
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TaggedRecordPagerVm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TaggedRecordPagerVm} obj Optional instance to populate.
    * @return {module:model/TaggedRecordPagerVm} The populated <code>TaggedRecordPagerVm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaggedRecordPagerVm();
                        
            
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('review')) {
                obj['review'] = ApiClient.convertToType(data['review'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = TagArticleStatusEnum.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('taggerNickName')) {
                obj['taggerNickName'] = ApiClient.convertToType(data['taggerNickName'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} page
    */
    'page' = undefined;
    /**
    * @member {Number} size
    */
    'size' = undefined;
    /**
    * @member {Boolean} review
    */
    'review' = undefined;
    /**
    * @member {module:model/TagArticleStatusEnum} status
    */
    'status' = undefined;
    /**
    * @member {String} taggerNickName
    */
    'taggerNickName' = undefined;




}
