/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TagRoleEnum.
* @enum {}
* @readonly
*/
export default class TagRoleEnum {
        /**
         * value: 0
         * @const
         */
        Tagger = 0;

        /**
         * value: 1
         * @const
         */
        Manager = 1;


    /**
    * Returns a <code>TagRoleEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TagRoleEnum} The enum <code>TagRoleEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
