/*
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TagRoleEnum} from './TagRoleEnum';

/**
 * The UserLoginResponse model module.
 * @module model/UserLoginResponse
 * @version v1
 */
export class UserLoginResponse {
  /**
   * Constructs a new <code>UserLoginResponse</code>.
   * @alias module:model/UserLoginResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserLoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserLoginResponse} obj Optional instance to populate.
   * @return {module:model/UserLoginResponse} The populated <code>UserLoginResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserLoginResponse();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('userName'))
        obj.userName = ApiClient.convertToType(data['userName'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = TagRoleEnum.constructFromObject(data['role']);
      if (data.hasOwnProperty('roleName'))
        obj.roleName = ApiClient.convertToType(data['roleName'], 'String');
      if (data.hasOwnProperty('canSkipTimesPerDay'))
        obj.canSkipTimesPerDay = ApiClient.convertToType(data['canSkipTimesPerDay'], 'Number');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} userId
 */
UserLoginResponse.prototype.userId = undefined;

/**
 * @member {String} userName
 */
UserLoginResponse.prototype.userName = undefined;

/**
 * @member {String} email
 */
UserLoginResponse.prototype.email = undefined;

/**
 * @member {String} token
 */
UserLoginResponse.prototype.token = undefined;

/**
 * @member {module:model/TagRoleEnum} role
 */
UserLoginResponse.prototype.role = undefined;

/**
 * @member {String} roleName
 */
UserLoginResponse.prototype.roleName = undefined;

/**
 * @member {Number} canSkipTimesPerDay
 */
UserLoginResponse.prototype.canSkipTimesPerDay = undefined;

/**
 * @member {Number} version
 */
UserLoginResponse.prototype.version = undefined;

