/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TagRoleEnum from './TagRoleEnum';

/**
* The UserLoginResponse model module.
* @module model/UserLoginResponse
* @version v1
*/
export default class UserLoginResponse {
    /**
    * Constructs a new <code>UserLoginResponse</code>.
    * @alias module:model/UserLoginResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserLoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserLoginResponse} obj Optional instance to populate.
    * @return {module:model/UserLoginResponse} The populated <code>UserLoginResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserLoginResponse();
                        
            
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = TagRoleEnum.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('roleName')) {
                obj['roleName'] = ApiClient.convertToType(data['roleName'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} userId
    */
    'userId' = undefined;
    /**
    * @member {String} userName
    */
    'userName' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {String} token
    */
    'token' = undefined;
    /**
    * @member {module:model/TagRoleEnum} role
    */
    'role' = undefined;
    /**
    * @member {String} roleName
    */
    'roleName' = undefined;




}
