/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HttpCodeEnum from './HttpCodeEnum';
import UserLoginResponse from './UserLoginResponse';

/**
* The UserLoginResponseResponse model module.
* @module model/UserLoginResponseResponse
* @version v1
*/
export default class UserLoginResponseResponse {
    /**
    * Constructs a new <code>UserLoginResponseResponse</code>.
    * @alias module:model/UserLoginResponseResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserLoginResponseResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserLoginResponseResponse} obj Optional instance to populate.
    * @return {module:model/UserLoginResponseResponse} The populated <code>UserLoginResponseResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserLoginResponseResponse();
                        
            
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('httpCode')) {
                obj['httpCode'] = ApiClient.convertToType(data['httpCode'], 'Number');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = HttpCodeEnum.constructFromObject(data['errorCode']);
            }
            if (data.hasOwnProperty('errorMsg')) {
                obj['errorMsg'] = ApiClient.convertToType(data['errorMsg'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = UserLoginResponse.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('errorMsgModel')) {
                obj['errorMsgModel'] = ApiClient.convertToType(data['errorMsgModel'], {'String': ['String']});
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} success
    */
    'success' = undefined;
    /**
    * @member {Number} httpCode
    */
    'httpCode' = undefined;
    /**
    * @member {module:model/HttpCodeEnum} errorCode
    */
    'errorCode' = undefined;
    /**
    * @member {String} errorMsg
    */
    'errorMsg' = undefined;
    /**
    * @member {module:model/UserLoginResponse} result
    */
    'result' = undefined;
    /**
    * @member {Object.<String, Array.<String>>} errorMsgModel
    */
    'errorMsgModel' = undefined;




}
