/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UserVm model module.
* @module model/UserVm
* @version v1
*/
export default class UserVm {
    /**
    * Constructs a new <code>UserVm</code>.
    * @alias module:model/UserVm
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserVm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserVm} obj Optional instance to populate.
    * @return {module:model/UserVm} The populated <code>UserVm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserVm();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('nickName')) {
                obj['nickName'] = ApiClient.convertToType(data['nickName'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {String} nickName
    */
    'nickName' = undefined;




}
