/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The WorkloadItem model module.
* @module model/WorkloadItem
* @version v1
*/
export default class WorkloadItem {
    /**
    * Constructs a new <code>WorkloadItem</code>.
    * @alias module:model/WorkloadItem
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>WorkloadItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WorkloadItem} obj Optional instance to populate.
    * @return {module:model/WorkloadItem} The populated <code>WorkloadItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkloadItem();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('nickName')) {
                obj['nickName'] = ApiClient.convertToType(data['nickName'], 'String');
            }
            if (data.hasOwnProperty('untagged')) {
                obj['untagged'] = ApiClient.convertToType(data['untagged'], 'String');
            }
            if (data.hasOwnProperty('tagging')) {
                obj['tagging'] = ApiClient.convertToType(data['tagging'], 'String');
            }
            if (data.hasOwnProperty('tagged')) {
                obj['tagged'] = ApiClient.convertToType(data['tagged'], 'String');
            }
            if (data.hasOwnProperty('unaudited')) {
                obj['unaudited'] = ApiClient.convertToType(data['unaudited'], 'String');
            }
            if (data.hasOwnProperty('audited')) {
                obj['audited'] = ApiClient.convertToType(data['audited'], 'String');
            }
            if (data.hasOwnProperty('unsanctioned')) {
                obj['unsanctioned'] = ApiClient.convertToType(data['unsanctioned'], 'String');
            }
            if (data.hasOwnProperty('unavail')) {
                obj['unavail'] = ApiClient.convertToType(data['unavail'], 'String');
            }
            if (data.hasOwnProperty('preProcessed')) {
                obj['preProcessed'] = ApiClient.convertToType(data['preProcessed'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {String} nickName
    */
    'nickName' = undefined;
    /**
    * @member {String} untagged
    */
    'untagged' = undefined;
    /**
    * @member {String} tagging
    */
    'tagging' = undefined;
    /**
    * @member {String} tagged
    */
    'tagged' = undefined;
    /**
    * @member {String} unaudited
    */
    'unaudited' = undefined;
    /**
    * @member {String} audited
    */
    'audited' = undefined;
    /**
    * @member {String} unsanctioned
    */
    'unsanctioned' = undefined;
    /**
    * @member {String} unavail
    */
    'unavail' = undefined;
    /**
    * @member {String} preProcessed
    */
    'preProcessed' = undefined;
    /**
    * @member {String} count
    */
    'count' = undefined;




}
