/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TagArticleStatusEnum from './TagArticleStatusEnum';

/**
* The WorkloadVm model module.
* @module model/WorkloadVm
* @version v1
*/
export default class WorkloadVm {
    /**
    * Constructs a new <code>WorkloadVm</code>.
    * @alias module:model/WorkloadVm
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>WorkloadVm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WorkloadVm} obj Optional instance to populate.
    * @return {module:model/WorkloadVm} The populated <code>WorkloadVm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkloadVm();
                        
            
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('articleStatus')) {
                obj['articleStatus'] = TagArticleStatusEnum.constructFromObject(data['articleStatus']);
            }
            if (data.hasOwnProperty('pageIndex')) {
                obj['pageIndex'] = ApiClient.convertToType(data['pageIndex'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Date} startDate
    */
    'startDate' = undefined;
    /**
    * @member {Date} endDate
    */
    'endDate' = undefined;
    /**
    * @member {module:model/TagArticleStatusEnum} articleStatus
    */
    'articleStatus' = undefined;
    /**
    * @member {Number} pageIndex
    */
    'pageIndex' = undefined;
    /**
    * @member {Number} pageSize
    */
    'pageSize' = undefined;




}
