/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkloadItem from './WorkloadItem';

/**
* The WorkloadDto model module.
* @module model/WorkloadDto
* @version v1
*/
export default class WorkloadDto {
    /**
    * Constructs a new <code>WorkloadDto</code>.
    * @alias module:model/WorkloadDto
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>WorkloadDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WorkloadDto} obj Optional instance to populate.
    * @return {module:model/WorkloadDto} The populated <code>WorkloadDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkloadDto();
                        
            
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], [WorkloadItem]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/WorkloadItem>} collection
    */
    'collection' = undefined;
    /**
    * @member {String} total
    */
    'total' = undefined;




}
