/*
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HttpCodeEnum} from './HttpCodeEnum';
import {WorkloadDto} from './WorkloadDto';

/**
 * The WorkloadDtoResponse model module.
 * @module model/WorkloadDtoResponse
 * @version v1
 */
export class WorkloadDtoResponse {
  /**
   * Constructs a new <code>WorkloadDtoResponse</code>.
   * @alias module:model/WorkloadDtoResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WorkloadDtoResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkloadDtoResponse} obj Optional instance to populate.
   * @return {module:model/WorkloadDtoResponse} The populated <code>WorkloadDtoResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkloadDtoResponse();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('httpCode'))
        obj.httpCode = ApiClient.convertToType(data['httpCode'], 'Number');
      if (data.hasOwnProperty('errorCode'))
        obj.errorCode = HttpCodeEnum.constructFromObject(data['errorCode']);
      if (data.hasOwnProperty('errorMsg'))
        obj.errorMsg = ApiClient.convertToType(data['errorMsg'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = WorkloadDto.constructFromObject(data['result']);
      if (data.hasOwnProperty('errorMsgModel'))
        obj.errorMsgModel = ApiClient.convertToType(data['errorMsgModel'], {'String': ['String']});
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
WorkloadDtoResponse.prototype.success = undefined;

/**
 * @member {Number} httpCode
 */
WorkloadDtoResponse.prototype.httpCode = undefined;

/**
 * @member {module:model/HttpCodeEnum} errorCode
 */
WorkloadDtoResponse.prototype.errorCode = undefined;

/**
 * @member {String} errorMsg
 */
WorkloadDtoResponse.prototype.errorMsg = undefined;

/**
 * @member {module:model/WorkloadDto} result
 */
WorkloadDtoResponse.prototype.result = undefined;

/**
 * @member {Object.<String, Array.<String>>} errorMsgModel
 */
WorkloadDtoResponse.prototype.errorMsgModel = undefined;

