/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The WorkloadItem model module.
* @module model/WorkloadItem
* @version v1
*/
export default class WorkloadItem {
    /**
    * Constructs a new <code>WorkloadItem</code>.
    * @alias module:model/WorkloadItem
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>WorkloadItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WorkloadItem} obj Optional instance to populate.
    * @return {module:model/WorkloadItem} The populated <code>WorkloadItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkloadItem();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {Number} count
    */
    'count' = undefined;




}
