/*
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ArticleDtoResponse} from '../model/ArticleDtoResponse';
import {ArticleRecordRequest} from '../model/ArticleRecordRequest';
import {AuditArticleRequest} from '../model/AuditArticleRequest';
import {BooleanResponse} from '../model/BooleanResponse';
import {TaggedRecordDtoResponse} from '../model/TaggedRecordDtoResponse';
import {TaggedRecordPagerVm} from '../model/TaggedRecordPagerVm';
import {TaggerDtoResponse} from '../model/TaggerDtoResponse';
import {WorkloadDtoResponse} from '../model/WorkloadDtoResponse';
import {WorkloadVm} from '../model/WorkloadVm';

/**
* Article service.
* @module api/ArticleApi
* @version v1
*/
export class ArticleApi {

    /**
    * Constructs a new ArticleApi. 
    * @alias module:api/ArticleApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiArticleAuditArticlePost operation.
     * @callback moduleapi/ArticleApi~apiArticleAuditArticlePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BooleanResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/AuditArticleRequest} opts.body 
     * @param {module:api/ArticleApi~apiArticleAuditArticlePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleAuditArticlePost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = BooleanResponse;

      return this.apiClient.callApi(
        '/api/Article/AuditArticle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleCheckCanAuditPost operation.
     * @callback moduleapi/ArticleApi~apiArticleCheckCanAuditPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BooleanResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.articleId 
     * @param {module:api/ArticleApi~apiArticleCheckCanAuditPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleCheckCanAuditPost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'articleId': opts['articleId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = BooleanResponse;

      return this.apiClient.callApi(
        '/api/Article/CheckCanAudit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleCheckCanEditPost operation.
     * @callback moduleapi/ArticleApi~apiArticleCheckCanEditPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BooleanResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.articleId 
     * @param {module:api/ArticleApi~apiArticleCheckCanEditPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleCheckCanEditPost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'articleId': opts['articleId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = BooleanResponse;

      return this.apiClient.callApi(
        '/api/Article/CheckCanEdit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleDistributeArticlePost operation.
     * @callback moduleapi/ArticleApi~apiArticleDistributeArticlePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArticleDtoResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.taggerId 
     * @param {module:api/ArticleApi~apiArticleDistributeArticlePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleDistributeArticlePost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'taggerId': opts['taggerId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = ArticleDtoResponse;

      return this.apiClient.callApi(
        '/api/Article/DistributeArticle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleGetTaggerInfoByArticleTaggedRecordIdPost operation.
     * @callback moduleapi/ArticleApi~apiArticleGetTaggerInfoByArticleTaggedRecordIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaggerDtoResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.recordId 
     * @param {module:api/ArticleApi~apiArticleGetTaggerInfoByArticleTaggedRecordIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleGetTaggerInfoByArticleTaggedRecordIdPost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'recordId': opts['recordId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = TaggerDtoResponse;

      return this.apiClient.callApi(
        '/api/Article/GetTaggerInfoByArticleTaggedRecordId', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleGetTaggersCanAuditArticlePost operation.
     * @callback moduleapi/ArticleApi~apiArticleGetTaggersCanAuditArticlePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArticleDtoResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.taggerId 
     * @param {module:api/ArticleApi~apiArticleGetTaggersCanAuditArticlePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleGetTaggersCanAuditArticlePost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'taggerId': opts['taggerId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = ArticleDtoResponse;

      return this.apiClient.callApi(
        '/api/Article/GetTaggersCanAuditArticle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticlePagingAritclePost operation.
     * @callback moduleapi/ArticleApi~apiArticlePagingAritclePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaggedRecordDtoResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/TaggedRecordPagerVm} opts.body 
     * @param {module:api/ArticleApi~apiArticlePagingAritclePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticlePagingAritclePost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = TaggedRecordDtoResponse;

      return this.apiClient.callApi(
        '/api/Article/PagingAritcle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleSaveTaggedRecordPost operation.
     * @callback moduleapi/ArticleApi~apiArticleSaveTaggedRecordPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BooleanResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/ArticleRecordRequest} opts.body 
     * @param {module:api/ArticleApi~apiArticleSaveTaggedRecordPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleSaveTaggedRecordPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = BooleanResponse;

      return this.apiClient.callApi(
        '/api/Article/SaveTaggedRecord', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleSearchArticlePost operation.
     * @callback moduleapi/ArticleApi~apiArticleSearchArticlePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArticleDtoResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.articleId 
     * @param {module:api/ArticleApi~apiArticleSearchArticlePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleSearchArticlePost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'articleId': opts['articleId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = ArticleDtoResponse;

      return this.apiClient.callApi(
        '/api/Article/SearchArticle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleSetReviewArticlePost operation.
     * @callback moduleapi/ArticleApi~apiArticleSetReviewArticlePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BooleanResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.articleId 
     * @param {Boolean} opts.review 
     * @param {module:api/ArticleApi~apiArticleSetReviewArticlePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleSetReviewArticlePost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'articleId': opts['articleId'],'review': opts['review']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = BooleanResponse;

      return this.apiClient.callApi(
        '/api/Article/SetReviewArticle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleSetUnavailArticlePost operation.
     * @callback moduleapi/ArticleApi~apiArticleSetUnavailArticlePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BooleanResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.articleId 
     * @param {module:api/ArticleApi~apiArticleSetUnavailArticlePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleSetUnavailArticlePost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'articleId': opts['articleId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = BooleanResponse;

      return this.apiClient.callApi(
        '/api/Article/SetUnavailArticle', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleSubmitAuditPost operation.
     * @callback moduleapi/ArticleApi~apiArticleSubmitAuditPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BooleanResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.articleId 
     * @param {module:api/ArticleApi~apiArticleSubmitAuditPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleSubmitAuditPost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'articleId': opts['articleId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = BooleanResponse;

      return this.apiClient.callApi(
        '/api/Article/SubmitAudit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiArticleWorkloadPost operation.
     * @callback moduleapi/ArticleApi~apiArticleWorkloadPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WorkloadDtoResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/WorkloadVm} opts.body 
     * @param {module:api/ArticleApi~apiArticleWorkloadPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiArticleWorkloadPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = WorkloadDtoResponse;

      return this.apiClient.callApi(
        '/api/Article/workload', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}