/**
 * ArticleTag
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import BooleanResponse from '../model/BooleanResponse';
import UserVm from '../model/UserVm';
import WorkloadDtoResponse from '../model/WorkloadDtoResponse';
import WorkloadVm from '../model/WorkloadVm';

/**
* UserCenter service.
* @module api/UserCenterApi
* @version v1
*/
export default class UserCenterApi {

    /**
    * Constructs a new UserCenterApi. 
    * @alias module:api/UserCenterApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiUserCenterUserInfoPut operation.
     * @callback module:api/UserCenterApi~apiUserCenterUserInfoPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BooleanResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:api/UserCenterApi~apiUserCenterUserInfoPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BooleanResponse}
     */
    apiUserCenterUserInfoPut(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = BooleanResponse;

      return this.apiClient.callApi(
        '/api/UserCenter/user/info', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiUserCenterWorkloadPost operation.
     * @callback module:api/UserCenterApi~apiUserCenterWorkloadPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/WorkloadDtoResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:api/UserCenterApi~apiUserCenterWorkloadPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/WorkloadDtoResponse}
     */
    apiUserCenterWorkloadPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = WorkloadDtoResponse;

      return this.apiClient.callApi(
        '/api/UserCenter/workload', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
